[railway]
  builder = "nixpacks"
  buildCommand = "npm install && npx prisma generate && npx nest build"
  startCommand = "npm run start:prod"

[nixpacks]
  node_version = "20"

[variables]
  NODE_ENV = "production"
  PORT = "4000"
